#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: ro

  # Disable SSH in the installer, or packer will fail to connect and stop the install
  early-commands:
    - systemctl stop ssh

  network:
    network:
      version: 2
      ethernets:
        enp0s3:
          dhcp4: yes
        enp0s8:
          dhcp4: yes
        eth0:
          dhcp4: yes
        eth1:
          dhcp4: yes

  apt:
      preserve_sources_list: false
      primary:
          - arches: [i386, amd64]
            uri: "http://archive.ubuntu.com/ubuntu"
          - arches: [default]
            uri: "http://ports.ubuntu.com/ubuntu-ports"
      geoip: true

  storage:
    layout:
      name: direct


  identity:
    hostname: ${hostname}.local
    username: ${user.username}
    password: ${user.password}

  ssh:
    install-server: yes
    allow-pw: true

  packages:
    - htop
    - nano
    - tar
    - vim
    - git
    - tmux

  user-data:
    disable_root: true

  late-commands:
    - sed -ie 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /target/etc/default/grub
    - sed -ie 's/^\(GRUB_CMDLINE_LINUX_DEFAULT\)=.*/\1="net.ifnames=0 modprobe.blacklist=floppy console=ttyS0,115200n8 no_timer_check edd=off"/' /target/etc/default/grub
