- name: Provision image
  hosts: default
  become: true

  tasks:
    - name: Clean cloud-init artifacts
      command:
        cmd: cloud-init clean

    - name: Purge unnecessary packages
      apt:
        name:
          - snapd
          - linux-firmware
          - linux-headers*
          - cloud-init*
        state: absent
        purge: yes
        autoremove: yes

    - name: Prevent snap reinstallation
      apt:
        name:
          -snapd
        state: hold

    - name: Update grub configuration
      command: update-grub2

    - import_tasks: _install_packages.yml

    - name: Update root password
      user:
        name: root
        update_password: always
        # python -c 'import crypt; print(crypt.crypt("root", "$1$NaCl$"))'
        password: $1$NaCl$Mb6A.7Qvm5pyF/2OFUCum0

    - name: Configure git for root and student
      become: yes
      shell: |
        git config --global color.ui auto
        git config --global user.name '{{ item.git_name }}'
        git config --global user.email '{{ item.git_email }}'
      loop:
        - { user: student, git_name: 'Student USO VM User', git_email: 'student@stud.acs.upb.ro' }
        - { user: root, git_name: 'Root USO VM User', git_email: 'root@stud.acs.upb.ro' }
      loop_control:
        loop_var: item
      become_user: "{{ item.user }}"

    - name: Clone the main repository
      become: yes
      become_user: student
      git:
        repo: https://github.com/systems-cs-pub-ro/uso-lab
        dest: /home/student/uso-lab.git

    - name: Clone razvand useful repository
      become: yes
      become_user: student
      git:
        repo: https://github.com/razvand/snippets
        dest: /home/student/Documents/snippets.git

    - name: Make Vim default editor
      command:
        cmd: update-alternatives --set editor /usr/bin/vim.basic

    - name: Configure Vim globally
      copy:
        src: /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope
        dest: /etc/vim/vimrc

    - name: Add additional Vim configuration
      become: yes
      become_user: student
      shell: |
        mkdir -p /home/student/.vim/bkup
        cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /home/student/.vimrc
        cp -r /home/student/Documents/snippets.git/config/vim/ftplugin/ /home/student/.vim/

    - name: Append additional settings to .vimrc
      become: yes
      become_user: student
      shell: |
        echo "set nocompatible" >> /home/student/.vimrc
        echo "set bs=2" >> /home/student/.vimrc

    - name: Root - Add additional Vim configuration
      shell: |
        mkdir -p /root/.vim/bkup
        cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /root/.vimrc
        cp -r /home/student/Documents/snippets.git/config/vim/ftplugin/ /root/.vim/

    - name: Append additional settings to .vimrc
      shell: |
        echo "set nocompatible" >> /root/.vimrc
        echo "set bs=2" >> /root/.vimrc

    - name: Set collation to show capitalized names first
      command:
        cmd: update-locale LC_COLLATE=C

    - name: Add additional Bash aliases for student
      become: yes
      become_user: student
      copy:
        src: /home/student/Documents/snippets.git/config/bash/bash_aliases_deploy_systemd
        dest: /home/student/.bash_aliases

    - name: Add additional Bash aliases for root
      copy:
        src: /home/student/Documents/snippets.git/config/bash/bash_aliases_deploy_systemd
        dest: /root/.bash_aliases

    - name: Trim Bash prompt when too large
      command:
        cmd: echo -e '\nexport PROMPT_DIRTRIM=3' >> /etc/bash.bashrc

    - name: Add i386 architecture
      command: dpkg --add-architecture i386

    - name: Add tmux configuration
      become: yes
      become_user: student
      copy:
        src: /home/student/Documents/snippets.git/config/tmux/tmux_debian.conf
        dest: /home/student/.tmux.conf

    - name: Add tmux configuration for root
      copy:
        src: /home/student/Documents/snippets.git/config/tmux/tmux_debian.conf
        dest: /root/.tmux.conf

    - name: Disable automated screen locking
      become: yes
      become_user: student
      shell: |
        gsettings set org.gnome.desktop.screensaver lock-enabled false
        gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false

    - name: Configure Favorites bar
      shell: |
        gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed s/.$//), 'org.gnome.Terminal.desktop']"
        gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed s/.$//), 'firefox.desktop']"

    - name: Clean command history for student and root
      shell: |
        history -c
        unset HISTFILE
        rm -f {{ user_home }}/bash_history
      become: yes
      become_user: "{{ item.user }}"
      vars:
        user_home: "{{ item.home }}"
      loop:
        - { user: 'student', home: '/home/student' }
        - { user: 'root', home: '/root' }
