- name: Provision image
  hosts: localhost
  become: true

  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: full

    - name: Update grub configuration
      command: update-grub2

    - name: Install required packages
      apt:
        pkg:
          - git
          - vim
        state: latest
        update_cache: true

    - name: Configure Git
      become: yes
      become_user: student
      shell: |
        git config --global color.ui auto
        git config --global user.name 'Student USO VM User'
        git config --global user.email 'student@stud.acs.upb.ro'

    - name: Root - Configure Git
      shell: |
        git config --global color.ui auto
        git config --global user.name 'Root USO VM User'
        git config --global user.email 'student@stud.acs.upb.ro'

    - name: Clone Razvan's scripts and configs in the Documents folder
      become: yes
      become_user: student
      git:
        repo: https://github.com/razvand/snippets
        dest: /home/student/Documents/snippets.git

    - name: Make Vim default editor
      command:
        cmd: update-alternatives --set editor /usr/bin/vim.basic

    - name: Configure Vim globally
      copy:
        src: /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope
        dest: /etc/vim/vimrc

    - name: Add additional Vim configuration
      become: yes
      become_user: student
      shell: |
        mkdir -p /home/student/.vim/bkup
        cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /home/student/.vimrc
        cp -r /home/student/Documents/snippets.git/config/vim/ftplugin/ /home/student/.vim/

    - name: Root - Add additional Vim configuration
      shell: |
        mkdir -p /root/.vim/bkup
        cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /root/.vimrc
        cp -r /home/student/Documents/snippets.git/config/vim/ftplugin/ /root/.vim/

    - name: Set collation to show capitalized names first
      command:
        cmd: update-locale LC_COLLATE=C

    - name: Add additional Bash aliases for student
      become: yes
      become_user: student
      copy:
        src: /home/student/Documents/snippets.git/config/bash/bash_aliases_deploy_systemd
        dest: /home/student/.bash_aliases

    - name: Add additional Bash aliases for root
      copy:
        src: /home/student/Documents/snippets.git/config/bash/bash_aliases_deploy_systemd
        dest: /root/.bash_aliases

    - name: Trim Bash prompt when too large
      command:
        cmd: echo -e '\nexport PROMPT_DIRTRIM=3' >> /etc/bash.bashrc

    - name: Install minimal GUI Debian packages
      apt:
        pkg:
          - xsel
          - xclip
          - scrot
          - shutter
          - less
          - htop
          - zip
          - unzip
          - vim-nox
          - git
          - subversion
          - lsof
          - build-essential
          - gdb
          - cscope
          - exuberant-ctags
          - strace
          - ltrace
          - valgrind
          - gawk
          - bash-completion
          - expect
          - netcat
          - telnet
          - lynx
          - curl
          - ncftp
          - host
          - dnsutils
          - openssh-server
          - smbclient
          - cifs-utils
          - ldap-utils
          - finger
          - pciutils
          - usbutils
          - lshw
          - mc
          - tree
          - apt-file
          - genisoimage
          - tcpdump
          - nmap
          - manpages-posix
          - manpages-posix-dev
          - make-doc
          - glibc-doc-reference
          - pwgen
          - lshw
          - inxi
          - emacs
          - org-mode
          - emacs-goodies-el
          - screen
          - tmux
          - tmux-plugin-manager
          - ethtool
          - net-tools
          - imagemagick
          - pdftk
          - iotop
          - sysstat
          - unrar
          - p7zip
          - lzma
          - xz-utils
          - moreutils
          - firefox
          - gedit
          - vlc
          - libreoffice
          - rhythmbox
          - gnome-mines
        state: latest
        update_cache: true

    - name: Add i386 architecture
      command: dpkg --add-architecture i386

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - gcc-multilib
          - libc6-i386
        state: present

    - name: Add tmux configuration
      become: yes
      become_user: student
      copy:
        src: /home/student/Documents/snippets.git/config/tmux/tmux_debian.conf
        dest: /home/student/.tmux.conf

    - name: Add tmux configuration for root
      copy:
        src: /home/student/Documents/snippets.git/config/tmux/tmux_debian.conf
        dest: /root/.tmux.conf

    - name: Update root password
      user:
        name: root
        update_password: always
        # python -c 'import crypt; print(crypt.crypt("root", "$1$NaCl$"))'
        password: $1$NaCl$Mb6A.7Qvm5pyF/2OFUCum0

    - name: Disable automated screen locking
      become: yes
      become_user: student
      shell: |
        gsettings set org.gnome.desktop.screensaver lock-enabled false
        gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false

    - name: Configure Favorites bar
      shell: |
        gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed s/.$//), 'org.gnome.Terminal.desktop']"
        gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed s/.$//), 'firefox.desktop']"

    - name: Set the timezone to 'Bucharest'
      file:
        src: /usr/share/zoneinfo/Europe/Bucharest
        dest: /etc/localtime
        state: link

    - name: Update, upgrade and clean
      shell: |
       apt update
       apt upgrade
       apt dist-upgrade
       apt clean
       apt autoclean
       apt autoremove

    - name: Clone USO repository
      become: yes
      become_user: student
      git:
        repo: https://github.com/systems-cs-pub-ro/uso-lab
        dest: ~/uso-lab.git

    - name: Clean command history
      become: yes
      become_user: student
      shell: |
        history -c
        unset HISTFILE
        rm -f /home/student/bash_history

    - name: Root - Clean command history
      shell: |
        history -c
        unset HISTFILE
        rm -f /root/bash_history
