- name: Provision image
  hosts: default
  become: true

  tasks:
    - import_tasks: _common.yml

    - name: Clean cloud-init artifacts
      command:
        cmd: cloud-init clean

    - name: Purge the unnecessary packages
      apt:
        name:
          - snapd
          - linux-firmware
          - linux-headers*
          - cloud-init*
        state: absent
        purge: yes
        autoremove: yes

    - name: Upgrade all packages
      apt:
        upgrade: full

    - name: Install additional packages
      apt:
        pkg:
          - emacs
          - firefox
          - ubuntu-desktop-minimal
        state: latest
        update_cache: true

    - name: Update grub configuration
      command: update-grub2

    - name: Configure Git
      become: yes
      become_user: student
      shell: |
        git config --global color.ui auto
        git config --global user.name 'Student USO VM User'
        git config --global user.email 'student@stud.acs.upb.ro'

    - name: Root - Configure Git
      shell: |
        git config --global color.ui auto
        git config --global user.name 'Root USO VM User'
        git config --global user.email 'student@stud.acs.upb.ro'

    - name: Clone Razvan's scripts and configs in the Documents folder
      become: yes
      become_user: student
      command:
        cmd: git clone https://github.com/razvand/snippets /home/student/Documents/snippets.git

    - name: Make Vim default editor
      command:
        cmd: update-alternatives --set editor /usr/bin/vim.basic

    - name: Configure Vim globally
      command:
        cmd: cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /etc/vim/vimrc

    - name: Add aditional Vim configuration
      become: yes
      become_user: student
      shell: |
        mkdir -p /home/student/.vim/bkup
        cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /home/student/.vimrc
        cp -r /home/student/Documents/snippets.git/config/vim/ftplugin/ /home/student/.vim/

    - name: Add aditional Vim configuration Root -
      shell: |
        mkdir -p /root/.vim/bkup
        cp /home/student/Documents/snippets.git/config/vim/vimrc_no_cscope /root/.vimrc
        cp -r /home/student/Documents/snippets.git/config/vim/ftplugin/ /root/.vim/

    - name: Add aditional Emacs configuration
      become: yes
      become_user: student
      command:
        cmd: cp /home/student/Documents/snippets.git/config/emacs/emacs-to-deploy.el /home/student/.emacs

    - name: Add aditional Emacs configuration Root -
      command:
        cmd: cp /home/student/Documents/snippets.git/config/emacs/emacs-to-deploy.el /root/.emacs

    - name: Set collation to show capitalized names first
      command:
        cmd: update-locale LC_COLLATE=C

    - name: Add aditional Bash aliases
      become: yes
      become_user: student
      command:
        cmd: cp /home/student/Documents/snippets.git/config/bash/bash_aliases_deploy_systemd /home/student/.bash_aliases
    
    - name: Add aditional Bash aliases Root -
      command:
        cmd: cp /home/student/Documents/snippets.git/config/bash/bash_aliases_deploy_systemd /root/.bash_aliases

    - name: Trim Bash prompt when too large
      command:
        cmd: echo -e '\nexport PROMPT_DIRTRIM=3' >> /etc/bash.bashrc

    - name: Install minimal CLI Debian packages
      command:
        cmd: bash /home/student/Documents/snippets.git/debian/cli-minimal-debian-install

    - name: Install minimal GUI Debian packages
      apt:
        pkg:
          - xsel
          - xclip
          - scrot
          - shutter
        state: latest
        update_cache: true

    - name: Install i386 C development environment
      shell: |
        dpkg --add-architecture i386
        apt update
        apt install -y gcc-multilib libc6-i386

    - name: Add tmux configuration
      become: yes
      become_user: student
      command:
        cmd: cp /home/student/Documents/snippets.git/config/tmux/tmux_debian.conf /home/student/.tmux.conf

    - name: Add tmux configuration Root -
      command:
        cmd: cp /home/student/Documents/snippets.git/config/tmux/tmux_debian.conf /root/.tmux.conf

    - name: Update root password
      user:
        name: root
        update_password: always
        # python -c 'import crypt; print(crypt.crypt("root", "$1$NaCl$"))'
        password: $1$NaCl$Mb6A.7Qvm5pyF/2OFUCum0

    - name: Disable DNS usage in SSH server
      command:
        cmd: sed -i 's/#UseDNS no/UseDNS no/g' /etc/ssh/sshd_config

    - name: Increase MaxAuthTries for ssh to 10
      command:
        cmd: sed -i 's/##MaxAuthTries 6/MaxAuthTries 10/g' /etc/ssh/sshd_config 

    - name: Disable automated screen locking
      become: yes
      become_user: student
      shell: |
        gsettings set org.gnome.desktop.screensaver lock-enabled false
        gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false

    - name: Configure Favorites bar
      shell: |
        gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed s/.$//), 'org.gnome.Terminal.desktop']"
        gsettings set org.gnome.shell favorite-apps "$(gsettings get org.gnome.shell favorite-apps | sed s/.$//), 'firefox.desktop']"

    - name: Set the timezone to 'Bucharest'
      file:
        src: /usr/share/zoneinfo/Europe/Bucharest
        dest: /etc/localtime
        state: link

    - name: Update, upgrade and clean
      shell: |
       apt update
       apt upgrade
       apt dist-upgrade
       apt clean 
       apt autoclean
       apt autoremove

    - name: Clone USO repository
      become: yes
      become_user: student
      command:
        cmd: git clone https://github.com/systems-cs-pub-ro/uso-lab uso-lab.git

    - name: Clean command history
      become: yes
      become_user: student
      shell: |
        history -c
        unset HISTFILE
        rm -f /home/student/bash_history
 
    - name: Clean command history Root -
      shell: |
        history -c
        unset HISTFILE
        rm -f /root/bash_history

    - import_tasks: _disk_clean.yml
